### ISSUE TITLE
.gitignore file is missing

### ISSUE THREAD

**Issue by seanred360** [JordanAdair/advice-generator-app-main#1]
If you do not include a .gitignore file GitHub does not know which files should be ignored and then pushed to the repo. Currently your entire node_modules folder is in the repo. This makes the download size bigger for no reason. If you had a .env file with password in it, that would also have been pushed up and anyone can see it.

**Comment by JordanAdair** [comment]
It's in there, I just uploaded one folder too deep it seems. Thanks for bringing this to my attention!
