### ISSUE TITLE
#advice-quote-block does not show the fetched data on Firefox

### ISSUE THREAD

**Issue by seanred360** [JordanAdair/advice-generator-app-main#2]
You will  notice in the network tab that a get request is being made each time you click the button, but you get back the same advice object every time. This is because Firefox is caching the API call because Firefox thinks that the URL is the same so there is no need to get the data again.  One solution to this could be to make a function that searches the API for a random ID and get an advice back. This will make the URL different every time.

**Comment by JordanAdair** [comment]
This did the trick. Thanks, Sean!

**Comment by seanred360** [comment]
What you really should do is pass a no-cache header in your axios request, I cannot find a way to do this because that API is blocking it, so I think you are out of luck.

**Comment by JordanAdair** [comment]
Yeah, I found a solution online that suggested the same but couldn't figure it out. This works for now though, thanks again.
